### ISSUE TITLE
Why Ernie is downloading pre-trained model from server every time?

### ISSUE THREAD

**Issue by monk1337** [PaddlePaddle/ERNIE#511]
https://github.com/PaddlePaddle/ERNIE/blob/9b6c6837f85ca8b232237bb9001710d820e11b95/ernie/modeling_ernie.py#L193

I have a question regarding loading the pre-trained model. In this particular line, it's not checking if the pre-trained dir exist or not instead condition is directly downloading the model first with temp file dir.

Suggestion :

Instead of creating a tempdir, create one static dir and store the weights there later, check if the weights are there before downloading from URL.

**Comment by Meiyim** [comment]
the script check if previous downloaded model could be found in tempdir at this line:
https://github.com/PaddlePaddle/ERNIE/blob/9b6c6837f85ca8b232237bb9001710d820e11b95/ernie/file_utils.py#L29

so if your tempdir were removed every time, you have to downloaded it again.

Or, you can download and extract one from our [pretrained model list](https://github.com/PaddlePaddle/ERNIE/blob/develop/README.en.md#3-download-pretrained-models-optional)
and use directory path instead of model tag the load pretrained model:
```python 
ErnieModel.from_pretrained('/path/to/extracted_pretrained_weights/')
```


p.s.
you can change your logging level to `logging.DEBUG` to see more backend logs, which is much more helpful when debugging
